### ISSUE TITLE
Does not seem to work?

### ISSUE THREAD

**Issue by TerrorFactor** [schollz/find-maraudersmap#6]
The map does not seem to work. I joined the hackdude group, learned my location here, entered the name as "office==50.8xxxx=4.5xxxx=0" (the x-es are other numbers of course, without quotes). Tapped "track" and checked the map on my location, but nothing.
Also tried with my own group, also nothing.

There's not much to do, so I doubt I'm doing something wrong? 

Nifty tool by the way :)

**Comment by TerrorFactor** [comment]
Nevermind, it seems that it started working after a few minutes :)

**Comment by schollz** [comment]
Sorry, the server was down. It is up now.

**Comment by schollz** [comment]
I can see its working for you, let me know if you still have trouble finding yourself on the map. Its not the easiest thing to use, I admit!

**Comment by TerrorFactor** [comment]
It seems to work as expected now, thank you!
