### ISSUE TITLE
API endpoint 'makejson': responds with error 500

### ISSUE THREAD

**Issue by NicksonYap** [schollz/find-maraudersmap#7]
Hi,

makejson outputs error 500

I'm trying to track with groupname STEEPSHARK and it doesn't work either.

hackduke.json seems to give old output:

```
{"link": "asldfkjaslfd", "items": [{"title": "hadi", "description": "Location: t1, floor 1<br>Last seen: 2017-01-31 10:27:32<br><img src=\"/hadi.jpg\" width=\"180\" height=\"240\" alt=\"\" \\/>", "latitude": "35.70310921143897", "longitude": "51.4034168873529"}], "title": "Some title", "description": "asldkfjaksldjf", "generator": "https:\\/\\/www.flickr.com", "modified": "2016-11-19T20:01:45Z"}
```

I'm really looking forward to this~ possible to get it fixed?

Thanks!

**Comment by schollz** [comment]
Are you running this yourself or using the public server? The public server may need to be restarted as I haven't used it in awhile. I recommend cloning this and running it on your own computer

**Comment by NicksonYap** [comment]
Using the public server.
Your code in GitHub seems fine.
