### ISSUE TITLE
The coordinates are faked.

### ISSUE THREAD

**Issue by NicksonYap** [schollz/find-maraudersmap#8]
It's worth mentioning in README

That the GPS coordinates are faked with a random number based on name of the location...

**Comment by schollz** [comment]
@nicksonyap the GPS coordinates are not fake and I don't know what random number you refer to.  The name of the location *is* the GPS coordinate. They are inputted that way so that they can be displayed on a map.

**Comment by NicksonYap** [comment]
@schollz 

I was referring to this random number:
https://github.com/schollz/find-maraudersmap/blob/master/server.py#L71

basically what happens is that the location of the room is plotted on the map.

So technically the coordinates are real, just that random small deviation is added to make it look like the device is moving around in the room.

**Comment by schollz** [comment]
Ah! So this random number is a bit of a hack. In the case you have two people in the exact same position, this random number will make them move apart slightly so you can actually see both markers if you zoom in all the way.
